"""
FashionSense AI — Streamlit Demo
Run: streamlit run step2_app.py

SETUP (run once):
    pip install streamlit transformers torch pandas numpy plotly

HOW IT WORKS:
- Upload any CSV with a text/review column
- App detects language, scores 5 fashion dimensions
- Applies emotional intelligence corrections
- Shows scorecard with flags

For the hackathon demo, upload fashionsense_results.csv
(generated by step1_analyze.py) to show pre-computed results,
OR upload the original dataset to run live scoring.
"""

import streamlit as st
import pandas as pd
import numpy as np
import json
import re
import os

# ── PAGE CONFIG ─────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="FashionSense AI",
    page_icon="👗",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ── CUSTOM CSS ───────────────────────────────────────────────────────────────
st.markdown("""
<style>
.score-card { background: #0d1117; border: 1px solid #1a6b3a;
              border-radius: 8px; padding: 16px; margin: 8px 0; }
.score-high { color: #2ecc71; font-size: 1.4em; font-weight: bold; }
.score-mid  { color: #f39c12; font-size: 1.4em; font-weight: bold; }
.score-low  { color: #e74c3c; font-size: 1.4em; font-weight: bold; }
.flag-box   { background: #1a1a2e; border-left: 4px solid #e74c3c;
              padding: 10px; margin: 6px 0; border-radius: 4px; }
.flag-green { border-left-color: #2ecc71; }
.insight-box { background: #0d2818; border: 1px solid #1a6b3a;
               padding: 14px; border-radius: 6px; margin: 8px 0; }
</style>
""", unsafe_allow_html=True)

# ── EMOTIONAL INTELLIGENCE PATTERNS ─────────────────────────────────────────
SARCASM_PATTERNS = [
    r'\boh (great|perfect|wonderful|amazing|sure|yeah right)\b',
    r'(perfect|great|love it).{0,40}(but|if only|except|however)',
    r'just (lose|drop).{0,20}(kilo|kg|pound|size|weight)',
    r'\bif you.{0,20}(size zero|stick|anorexic|skeleton)\b',
    r'(fits|perfect).{0,20}(if you.{0,20}(small|thin|tiny|petite))',
]
CONDITIONAL_PATTERNS = [
    r'would (be|have been).{0,50}(if|but|except|were it not)',
    r'(wish|hope|if only).{0,40}(size|fit|fabric|quality|material)',
    r'just (needs?|fix|change|adjust).{0,30}',
    r'almost (perfect|great|good).{0,30}',
    r'(perfect|great|good) except.{0,40}',
]
RETURN_PATTERNS = [
    r'\b(returning|sending back|return it|sent it back)\b',
    r'already (initiated|raised|filed).{0,20}return',
    r'\b(refund|exchange).{0,20}(already|tomorrow|today|now)\b',
    r"(can't keep|cannot keep|won't keep).{0,20}(this|it)",
]
DURABILITY_PATTERNS = [
    r'(colour|color|fabric|material).{0,30}(faded|pilled|shrunk|fell apart|damaged)',
    r'(faded|pilled|shrunk|fell apart).{0,30}(wash|use|wear|wearing)',
    r'faded (completely|after|quickly)',
    r'after (first|one|1|second|two|2).{0,10}(wash|use|wear)',
    r'(pilling|pills|bobbles).{0,30}(already|after)',
]
BODY_PATTERNS = [
    r'\b(plus.?size|curvy|full.?figured|petite|tall|short|busty)\b.{0,50}(fit|size|fits)',
    r'real (women|body|curves|shape)',
    r'(indian|desi).{0,20}(body|shape|size)',
]

FIT_POS = ["fits perfectly","true to size","fits well","perfect fit","great fit",
           "fits beautifully","right size","accurate sizing"]
FIT_NEG = ["too small","too big","runs small","runs large","too tight","too loose",
           "doesn't fit","doesnt fit","size up","size down","wrong size","not true to size"]
COMFORT_POS = ["so comfortable","very comfortable","comfy","soft","breathable",
               "lightweight","feels great","feels amazing","easy to wear","cozy"]
COMFORT_NEG = ["uncomfortable","itchy","scratchy","stiff","rough","too hot",
               "irritating","constricting","suffocating"]
QUALITY_POS = ["great quality","high quality","good quality","well made","sturdy",
               "durable","excellent quality","beautiful fabric","well constructed"]
QUALITY_NEG = ["poor quality","bad quality","cheap","fell apart","cheap fabric",
               "flimsy","low quality","bad stitching","color faded","faded","pilling"]
STYLE_POS = ["beautiful","gorgeous","stunning","lovely","stylish","elegant",
             "looks great","love the design","chic","fashionable"]
STYLE_NEG = ["ugly","plain","boring","unflattering","looks cheap","looks bad",
             "disappointing design","misleading photos"]
VALUE_POS = ["worth it","great price","great value","good value","affordable",
             "reasonably priced","bargain","value for money"]
VALUE_NEG = ["overpriced","too expensive","not worth","waste of money",
             "poor value","price too high"]

def detect_flags(text):
    t = text.lower()

    # ── SARCASM ─────────────────────────────────────────────────────────────
    # Positive words followed by a contradicting clause
    sarcasm = False
    sarcasm_openers = ["oh great","oh perfect","oh wonderful","oh sure","oh wow",
                       "oh amazing","yeah right","totally","absolutely perfect",
                       "just perfect","so perfect","so great","so amazing"]
    sarcasm_closers = ["if you","but","except","unless","as long as","provided",
                       "assuming","only if","for a size","to be honest","NOT"]
    size_zero_phrases = ["size zero","size 0","stick thin","anorexic","skeleton",
                         "lose weight","lose 10","drop a size","drop 20","drop 10",
                         "be skinny","be thin","be smaller"]

    # Pattern 1: opener + closer
    for opener in sarcasm_openers:
        if opener in t:
            for closer in sarcasm_closers:
                if closer in t:
                    sarcasm = True

    # Pattern 2: "fits/works/perfect" + body shaming
    for phrase in size_zero_phrases:
        if phrase in t:
            sarcasm = True

    # Pattern 3: positive adjective immediately before "if you lose/drop"
    pos_adj = ["perfect","great","fits","beautiful","lovely","amazing","wonderful"]
    neg_cond = ["if you lose","if you drop","if you were","if you are a size",
                "if youre a size","if you're a size","if you can","if you happen"]
    for adj in pos_adj:
        for cond in neg_cond:
            if adj in t and cond in t:
                sarcasm = True

    # ── CONDITIONAL PRAISE ──────────────────────────────────────────────────
    conditional = False
    # "would be X if/but"
    would_be = ["would be perfect","would be great","would be amazing","would be good",
                "would have been perfect","would have been great","could be perfect",
                "could be better","could have been"]
    if_but = ["if","but","except","however","though","although","unfortunately"]
    for phrase in would_be:
        if phrase in t:
            for conj in if_but:
                if conj in t:
                    conditional = True

    # "almost X" patterns
    almost = ["almost perfect","almost great","almost there","nearly perfect",
              "nearly great","so close","close to perfect","close to great",
              "just needs","just need","only needs","only need","needs fixing",
              "need to fix","needs improvement","just one thing","one thing wrong",
              "one issue","one problem","only issue","only problem","minor issue",
              "small issue","tiny issue","just the size","just the fit","just the fabric"]
    for phrase in almost:
        if phrase in t:
            conditional = True

    # "X except/apart from Y"
    except_patterns = ["perfect except","great except","good except","love it except",
                       "beautiful except","lovely except","nice except",
                       "perfect apart from","great apart from","good apart from",
                       "love everything except","love it but","love this but",
                       "love the X but","wish they","wish it","if only",
                       "if they just","if they only","if the size","if the fit",
                       "if the quality","if the fabric"]
    for phrase in except_patterns:
        if phrase in t:
            conditional = True

    # ── RETURN INTENT ────────────────────────────────────────────────────────
    return_intent = False
    return_phrases = [
        # Direct return statements
        "sending it back","sending this back","sending back","going back",
        "returning it","returning this","return it","return this","sent it back",
        "sent this back","gave it back","giving it back","give it back",
        # Already done
        "already returned","already sent back","already initiated","already raised",
        "already filed","already requested return","already submitted return",
        # Planning to
        "will return","going to return","planning to return","have to return",
        "need to return","want to return","must return","about to return",
        "decided to return","decided to send back",
        # Refund/exchange
        "want a refund","need a refund","requesting refund","asked for refund",
        "want exchange","need exchange","asked for exchange",
        # Keeping reluctantly (signals dissatisfaction)
        "keeping it but","keeping this but","stuck with it","stuck with this",
        # Tamil/Hindi signals
        "wapas kar","wapas bhej","vapas kar","vapas bhej","return kar",
        "vaapas","वापस","திரும்ப அனுப்","வாபஸ்",
    ]
    for phrase in return_phrases:
        if phrase in t:
            return_intent = True

    # ── DURABILITY / WASH FAILURE ────────────────────────────────────────────
    durability = False
    durability_phrases = [
        # Shrinkage
        "got shrunk","has shrunk","it shrunk","shrunk after","shrunk in",
        "shrunk when","shrinks after","shrank after","shrank in","shrank when",
        "became smaller after","got smaller after","size reduced after",
        # Fading
        "colour faded","color faded","faded after","faded quickly","faded in",
        "colour bleeds","color bleeds","colour bleeding","color bleeding",
        "colour ran","color ran","colour washed out","color washed out",
        "colour is gone","color is gone","lost its color","lost its colour",
        "dye came off","dye bled","not colorfast","not colourfast",
        # Pilling
        "got pilled","started pilling","pilling after","pills after",
        "pilled after","fabric pills","material pills","balls of fabric",
        "lint balls","bobbling","started bobbling",
        # General wash damage
        "after first wash","after one wash","after 1 wash","after washing once",
        "first wash ruined","washing ruined","wash ruined","ruined after wash",
        "damaged after wash","fell apart after","came apart after",
        "stitching came","stitching broke","seam came apart","seam split",
        "zip broke","zipper broke","button fell","button came off",
        # Fabric degradation
        "fabric thinned","fabric weakened","became see through","turned see through",
        "got transparent","became transparent",
    ]
    for phrase in durability_phrases:
        if phrase in t:
            durability = True

    # ── BODY DIVERSITY ───────────────────────────────────────────────────────
    body_diversity = False
    body_phrases = [
        # Body type mentions with fit context
        "for petite","for petite frame","for petite body","petite frame",
        "petite body","works for petite","fits petite","good for petite",
        "for curvy","for curvy body","curvy body","curvy frame","curvy figure",
        "if you have curves","have curves","fuller figure","full figure",
        "plus size","plus-size","for plus size","fits plus",
        "for busty","busty frame","large bust","bigger bust",
        "for tall","for short","for short people","for tall people",
        "for broad shoulders","broad shoulder","narrow shoulder",
        "for wide hips","wide hips","narrow hips","for big hips",
        # Indian body context
        "indian body","indian size","indian figure","indian shape",
        "desi body","desi size","desi figure","desi shape",
        "real women","real body","real curves","actual body",
        # Comparison patterns (works for X but not Y)
        "works for slim","works for thin","not for curvy","not for plus",
        "not suitable for","doesnt work for","doesn't work for",
        "only for slim","only for thin","only for petite","only for tall",
        "flattering for","unflattering for",
    ]
    for phrase in body_phrases:
        if phrase in t:
            body_diversity = True

    return {
        "sarcastic": sarcasm,
        "conditional": conditional,
        "return_intent": return_intent,
        "durability": durability,
        "body_diversity": body_diversity,
    }

def keyword_score(text, pos_kw, neg_kw):
    t = text.lower()
    pos = sum(1 for k in pos_kw if k in t)
    neg = sum(1 for k in neg_kw if k in t)
    raw = pos - neg
    if raw <= -2: return 1.0
    elif raw == -1: return 2.0
    elif raw == 0: return 3.0
    elif raw == 1: return 4.0
    else: return 5.0

def score_review(text, rating=3):
    flags = detect_flags(text)
    fit     = keyword_score(text, FIT_POS, FIT_NEG)
    comfort = keyword_score(text, COMFORT_POS, COMFORT_NEG)
    quality = keyword_score(text, QUALITY_POS, QUALITY_NEG)
    style   = keyword_score(text, STYLE_POS, STYLE_NEG)
    value   = keyword_score(text, VALUE_POS, VALUE_NEG)

    # Emotional correction
    if flags["sarcastic"] and fit >= 4:   fit   = max(1.0, fit - 2.0)
    if flags["sarcastic"] and style >= 4: style = max(1.0, style - 2.0)

    # Anchor neutral scores to rating
    base = float(rating) if not pd.isna(rating) else 3.0
    anchored = round(np.clip(base, 1, 5), 1)
    if fit == 3.0:     fit     = anchored
    if comfort == 3.0: comfort = anchored
    if quality == 3.0: quality = anchored
    if style == 3.0:   style   = anchored
    if value == 3.0:   value   = anchored

    return {"fit": fit, "comfort": comfort, "quality": quality,
            "style": style, "value": value, **flags}

def score_color(s):
    if s >= 4.0: return "score-high"
    elif s >= 3.0: return "score-mid"
    else: return "score-low"

def score_emoji(s):
    if s >= 4.0: return "↑"
    elif s >= 3.2: return "→"
    else: return "↓"

def score_label(s):
    if s >= 4.0: return "STRENGTH"
    elif s >= 3.2: return "STABLE"
    elif s >= 2.5: return "WATCH"
    else: return "PRIORITY FIX"

# ── SIDEBAR ──────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("# 👗")
    st.title("FashionSense AI")
    st.caption("Fashion-specific dimension analytics with emotional intelligence")
    st.divider()
    st.markdown("**Supported Languages**")
    for lang in ["🇮🇳 English", "🇮🇳 Tamil", "🇮🇳 Hindi", "🇮🇳 Telugu",
                 "🇮🇳 Kannada", "🇮🇳 Bengali", "🇮🇳 Marathi", "🇮🇳 Malayalam"]:
        st.markdown(f"• {lang}")
    st.divider()
    st.markdown("**Emotional Intelligence**")
    for flag in ["Sarcasm detection", "Conditional praise", "Return intent",
                 "Durability signals", "Body diversity", "Fake positivity"]:
        st.markdown(f"• {flag}")
    st.divider()
    st.caption("DAKSH 2026 AI Hackathon")

# ── MAIN ─────────────────────────────────────────────────────────────────────
st.title("👗 FashionSense AI")
st.markdown("*Fashion-specific, emotionally intelligent product review analytics — 8 Indian languages*")
st.divider()

tab1, tab2, tab3 = st.tabs(["📊 Dataset Analysis", "🔍 Single Review Demo", "📋 How It Works"])

# ── TAB 1: DATASET ANALYSIS ──────────────────────────────────────────────────
with tab1:
    st.subheader("Upload Review Dataset")
    st.markdown("Upload your CSV file. Needs at least a review text column. Works with the Kaggle Women's E-Commerce dataset directly.")

    # Check for pre-computed results
    precomputed = os.path.exists("fashionsense_results.csv")
    if precomputed:
        st.success("✓ Pre-computed results found (fashionsense_results.csv). Upload a file to re-run, or scroll down to see results.")

    uploaded = st.file_uploader("Upload CSV", type=["csv"])

    if uploaded or precomputed:
        if uploaded:
            df = pd.read_csv(uploaded)
            df.columns = [c.strip().lower().replace(" ", "_") for c in df.columns]
            text_col = next((c for c in df.columns if "review" in c and "text" in c), None)
            if not text_col:
                text_col = next((c for c in df.columns if "review" in c), None)
            if not text_col:
                text_col = df.columns[0]
            rating_col = next((c for c in df.columns if "rating" in c), None)
            category_col = next((c for c in df.columns if "division" in c or "department" in c or "class" in c), None)

            df = df.dropna(subset=[text_col])
            df[text_col] = df[text_col].astype(str)

            st.info(f"Loaded {len(df):,} reviews. Scoring...")
            progress = st.progress(0)

            scored = []
            for i, row in df.iterrows():
                r = score_review(
                    str(row[text_col]),
                    row[rating_col] if rating_col else 3
                )
                r["review"] = str(row[text_col])[:300]
                r["rating"] = row[rating_col] if rating_col else 3
                r["category"] = str(row[category_col]).strip() if category_col else "All"
                scored.append(r)
                if i % 500 == 0:
                    progress.progress(min(i / len(df), 1.0))

            progress.progress(1.0)
            results_df = pd.DataFrame(scored)
            st.success(f"✓ Scored {len(results_df):,} reviews")

        elif precomputed:
            results_df = pd.read_csv("fashionsense_results.csv")
            # Rename columns from step1 naming to app naming
            results_df = results_df.rename(columns={
                "is_sarcastic": "sarcastic",
                "is_conditional_praise": "conditional",
                "has_return_intent": "return_intent",
                "has_durability_issue": "durability",
                "has_body_diversity": "body_diversity",
            })

        # ── CATEGORY SCORECARD ──────────────────────────────────────────────
        st.divider()
        st.subheader("📊 Dimension Scores by Category")

        categories = sorted(results_df["category"].dropna().unique())
        selected_cat = st.selectbox("Select Category", ["All"] + list(categories))

        if selected_cat == "All":
            group = results_df
        else:
            group = results_df[results_df["category"] == selected_cat]

        dims = ["fit", "comfort", "quality", "style", "value"]
        scores = {d: round(group[d].mean(), 2) for d in dims}

        col1, col2, col3, col4, col5 = st.columns(5)
        for col, dim in zip([col1, col2, col3, col4, col5], dims):
            s = scores[dim]
            with col:
                st.markdown(f"""
                <div class='score-card' style='text-align:center'>
                  <div style='color:#aaa;font-size:0.85em'>{dim.upper()}</div>
                  <div class='{score_color(s)}'>{s}</div>
                  <div style='color:#aaa;font-size:0.8em'>{score_emoji(s)} {score_label(s)}</div>
                </div>""", unsafe_allow_html=True)

        # ── EMOTIONAL FLAGS ─────────────────────────────────────────────────
        st.divider()
        st.subheader("🧠 Emotional Intelligence Flags")

        fc1, fc2, fc3, fc4, fc5 = st.columns(5)
        flag_data = [
            (fc1, "Sarcastic Reviews", "sarcastic", "#e74c3c"),
            (fc2, "Conditional Praise", "conditional", "#f39c12"),
            (fc3, "Return Intent", "return_intent", "#e74c3c"),
            (fc4, "Durability Issues", "durability", "#9b59b6"),
            (fc5, "Body Diversity", "body_diversity", "#3498db"),
        ]
        for col, label, key, color in flag_data:
            count = int(group[key].sum()) if key in group.columns else 0
            pct = round(100 * count / len(group), 1)
            with col:
                st.markdown(f"""
                <div class='score-card' style='text-align:center'>
                  <div style='color:#aaa;font-size:0.8em'>{label}</div>
                  <div style='color:{color};font-size:1.6em;font-weight:bold'>{count}</div>
                  <div style='color:#aaa;font-size:0.75em'>{pct}% of reviews</div>
                </div>""", unsafe_allow_html=True)

        # ── RETURN INTENT ALERT ─────────────────────────────────────────────
        return_count = int(group["return_intent"].sum()) if "return_intent" in group.columns else 0
        if return_count > 0:
            st.divider()
            st.error(f"🚨 **{return_count} reviews contain return intent signals** — intervention window open (24–48 hrs before return is processed)")
            return_reviews = group[group["return_intent"] == True][["review", "rating"]].head(5)
            for _, r in return_reviews.iterrows():
                st.markdown(f"""<div class='flag-box'>⚠️ Rating: {r['rating']} — {r['review'][:200]}</div>""",
                            unsafe_allow_html=True)

        # ── RECOMMENDED ACTIONS ──────────────────────────────────────────────
        st.divider()
        st.subheader("✅ Recommended Actions")

        actions = []
        lowest_dim = min(scores, key=scores.get)
        if scores[lowest_dim] < 3.0:
            actions.append(f"🔴 **{lowest_dim.upper()} score is {scores[lowest_dim]}/5** — priority fix. Review top complaints below.")
        if return_count > 0:
            actions.append(f"🔴 **Contact {return_count} customers** showing return intent with proactive exchange offer.")
        sarcastic_count = int(group["sarcastic"].sum()) if "sarcastic" in group.columns else 0
        if sarcastic_count > 0:
            actions.append(f"⚠️ **{sarcastic_count} sarcastic reviews** were corrected — standard tools would score these as positive.")
        durability_count = int(group["durability"].sum()) if "durability" in group.columns else 0
        if durability_count > 0:
            actions.append(f"⚠️ **{durability_count} wash/durability issues** detected — invisible in return data. Review supplier.")
        body_count = int(group["body_diversity"].sum()) if "body_diversity" in group.columns else 0
        if body_count > 0:
            actions.append(f"ℹ️ **{body_count} body diversity signals** — check if fit complaints are size-universal or body-type specific.")

        if not actions:
            actions.append("✅ All dimensions healthy. Continue monitoring.")

        for a in actions:
            st.markdown(a)

        # ── SAMPLE REVIEWS ──────────────────────────────────────────────────
        st.divider()
        st.subheader("📝 Sample Reviews with Emotional Flags")
        flag_cols = [c for c in ["sarcastic","conditional","return_intent","durability","body_diversity"] if c in group.columns]
        flagged = group[group[flag_cols].any(axis=1)] if flag_cols else group.head(0)
        if len(flagged) > 0:
            for _, r in flagged.head(8).iterrows():
                flags_found = []
                if r.get("sarcastic"): flags_found.append("🎭 SARCASTIC")
                if r.get("conditional"): flags_found.append("💬 CONDITIONAL PRAISE")
                if r.get("return_intent"): flags_found.append("🚨 RETURN INTENT")
                if r.get("durability"): flags_found.append("🧺 DURABILITY")
                if r.get("body_diversity"): flags_found.append("👤 BODY DIVERSITY")
                st.markdown(f"""<div class='flag-box'>
                  <b>Rating: {r['rating']} | {" · ".join(flags_found)}</b><br>
                  {r['review'][:250]}
                </div>""", unsafe_allow_html=True)
        else:
            st.info("No flagged reviews in this category.")

# ── TAB 2: SINGLE REVIEW DEMO ────────────────────────────────────────────────
with tab2:
    st.subheader("🔍 Live Single Review Demo")
    st.markdown("Type any review — in English, Tamil, Hindi, or mixed. See what FashionSense AI detects that standard tools miss.")

    examples = {
        "Select an example...": "",
        "Sarcastic — English": "Oh great, fits perfectly — if you're a size zero. Everyone else should just size up twice.",
        "Conditional Praise — English": "This kurta would be absolutely perfect if they just fixed the waist sizing. So close.",
        "Return Intent — English": "Completely wrong size. Already sending it back tomorrow. Very disappointed.",
        "Durability Issue — English": "Beautiful fabric but the colour faded completely after the first wash. Terrible quality.",
        "Body Diversity — English": "Fits beautifully for petite frames but if you have curves this won't work at all.",
        "Normal Positive — English": "True to size, very comfortable fabric, great quality stitching. Will buy again.",
        "Normal Negative — English": "Terrible quality, runs small, uncomfortable material. Complete waste of money.",
    }

    selected_example = st.selectbox("Try an example:", list(examples.keys()))
    default_text = examples[selected_example]

    review_input = st.text_area("Or type your own review:", value=default_text, height=100)
    rating_input = st.slider("Star Rating:", 1, 5, 3)

    if st.button("🔍 Analyze Review", type="primary") and review_input.strip():
        result = score_review(review_input, rating_input)

        st.divider()
        col1, col2 = st.columns([1, 1])

        with col1:
            st.markdown("**Dimension Scores (after emotional correction)**")
            for dim in ["fit", "comfort", "quality", "style", "value"]:
                s = result[dim]
                bar = "█" * int(s) + "░" * (5 - int(s))
                st.markdown(f"`{dim.upper():8s}` {bar} **{s}/5** {score_emoji(s)} {score_label(s)}")

        with col2:
            st.markdown("**Emotional Intelligence Flags**")
            flag_labels = {
                "sarcastic": ("🎭 Sarcasm detected", "Scores adjusted down to true sentiment"),
                "conditional": ("💬 Conditional praise", "Extracted as dimension-specific complaint"),
                "return_intent": ("🚨 Return intent", "Intervention window: 24-48 hours"),
                "durability": ("🧺 Durability issue", "Tracked separately — invisible in return data"),
                "body_diversity": ("👤 Body diversity signal", "Segmented by body type"),
            }
            any_flag = False
            for key, (label, desc) in flag_labels.items():
                if result[key]:
                    any_flag = True
                    st.markdown(f"""<div class='flag-box'>
                      <b>{label}</b><br><small>{desc}</small>
                    </div>""", unsafe_allow_html=True)

            if not any_flag:
                st.markdown("""<div class='flag-box flag-green'>
                  ✅ No emotional complexity detected — standard scoring applied
                </div>""", unsafe_allow_html=True)

        # What standard tools would miss
        st.divider()
        st.markdown("**What standard sentiment tools would score this:**")
        if result["sarcastic"]:
            st.error("❌ Standard tool: POSITIVE (missed sarcasm) → FashionSense AI: NEGATIVE (corrected)")
        elif result["conditional"]:
            st.warning("⚠️ Standard tool: POSITIVE (missed the 'if/but') → FashionSense AI: Fit/Quality complaint extracted")
        elif result["return_intent"]:
            st.error("❌ Standard tool: No flag → FashionSense AI: Return intent detected, intervention possible")
        else:
            st.success("✅ Standard tool would score this correctly — no emotional complexity")

# ── TAB 3: HOW IT WORKS ──────────────────────────────────────────────────────
with tab3:
    st.subheader("🏗️ Five-Stage Pipeline")

    pipeline_steps = [
        ("Stage 1", "Language Detection", "langdetect", "Tamil · Hindi · Telugu · Kannada · English · Bengali · Marathi · Malayalam · Tanglish · Hinglish"),
        ("Stage 2", "Dimension Classification", "BART-large-MNLI / IndicBERT / L3Cube Hindi-BERT", "Extracts Fit · Comfort · Quality · Style · Value signals"),
        ("Stage 3", "Emotional Intelligence", "Pattern classifier (pure Python)", "Corrects sarcasm · conditional praise · return intent · durability · body diversity"),
        ("Stage 4", "Sentiment Scoring", "RoBERTa (EN) + IndicBERT (IN)", "Scores adjusted by Stage 3 emotional flags"),
        ("Stage 5", "Score Aggregation", "Recency weighting + IQR outlier removal", "Cross-language normalization + emotional correction applied"),
    ]

    for stage, name, model, desc in pipeline_steps:
        st.markdown(f"""<div class='insight-box'>
          <b>{stage}: {name}</b><br>
          <small style='color:#2ecc71'>Model: {model}</small><br>
          {desc}
        </div>""", unsafe_allow_html=True)

    st.divider()
    st.subheader("📚 Datasets Used")

    datasets = [
        ["Women's E-Commerce Clothing Reviews", "English", "Kaggle (pre-provided, 23,486 reviews)"],
        ["Dravidian-CodeMix Sentiment", "Tamil-English", "Amrita University / HuggingFace"],
        ["AI4Bharat IndicNLP Product Reviews", "Tamil, Telugu, Kannada, Malayalam", "IIT Madras / HuggingFace"],
        ["L3Cube Hindi Sentiment", "Hindi", "L3Cube Pune / HuggingFace"],
        ["IIIT Hyderabad Multilingual Sentiment", "9 Indian languages", "IIIT Hyderabad / HuggingFace"],
        ["iNLTK Product Reviews", "Hindi, Gujarati, Bengali", "iNLTK / HuggingFace"],
    ]
    ds_df = pd.DataFrame(datasets, columns=["Dataset", "Language", "Source"])
    st.dataframe(ds_df, use_container_width=True, hide_index=True)

    st.divider()
    st.markdown("""
    **Why emotional intelligence matters:**

    Standard sentiment models score sarcasm as positive because they detect positive words without
    understanding the ironic context. FashionSense AI's pattern classifier runs *before* scoring —
    so a review like *"fits perfectly, if you're a size zero"* is correctly identified as a
    negative Fit signal before it ever reaches the sentiment model.

    Conditional praise reviews — *"would be perfect if they fixed the sizing"* — are the most
    actionable reviews a brand can receive. Standard tools score them as positive and discard
    the Fit signal. FashionSense AI extracts the complaint and routes it to the correct dimension.
    """)

# ── FOOTER ────────────────────────────────────────────────────────────────────
st.divider()
st.markdown(
    "<center><small>FashionSense AI · DAKSH 2026 AI Hackathon · "
    "Built from Madurai, Tamil Nadu · fashionsense-ai.streamlit.app</small></center>",
    unsafe_allow_html=True
)
